### PR TITLE
Naming changes, semicolons and new .when() snippet

### PR DESCRIPTION
**Pull request by pandeiro**
These are really helpful, but I'd also prefer shorter mnemonics.

I am not sure I agree with the snippet for controller. For ngc I would like a syntax similar to that of ngd, ngfa, etc:

```
.controller('$1', function($scope, $2) {
    $0
})
```

I'm also not sure about leaving the semicolons off everywhere. Routing is the only place in Angular where I usually chain a bunch of things; what do you guys think? I've gone ahead and added semicolons where appropriate, and excluded them from a new ngw. This new ngw snippet looks like this:

```
.when("/$1", {
  templateUrl: "$2",
  controller: "$0"
})
```

Let me know what you think.

### CODE REVIEW

**Comment by magnars** [comment]
What do you think of these, @lispnik? 

I think the names make a lot more sense. And I do like the semicolons.

One thing tho: The snippets starting with a `.` will be hard to use effectively. If I want to create a controller on `app`, I can't type `appngc` and press tab. Maybe remove the dot prefix, and I could do `app.ngc` tab?

**Comment by magnars** [comment]
It is also entirely possible to create a little function that will add a dot if it is missing, like if you're adding it on a new line.

**Comment by pandeiro** [comment]
Ah ok, I'm not so familiat with yas so I didn't realize that the expansion wouldn't work by typing, eg `appngc`. Sorry about that. So I see three possibilities:
- I can change the snippets to exclude the dot.
- I'm not sure how to write the function that checks for the dot and adds it if necessary, but one of you could contribute that or give me an example?
- I could change the snippet so that $1 is before the dot, so you would use eg `ngc` and then add the module, then the additional dependencies to inject, and then the body of the function. (Maybe this is less flexible, though...)

What do you think?

**Comment by magnars** [comment]
If you remove the dot, I can take a look at adding it if needed. :)

**Comment by magnars** [comment]
Seems like we won't get a response from lispnik, so I'm merging this. Thanks for both of your efforts. :-)

**Pull request merged**
